In [2]:
import numpy as np

array([0.72771654, 1.62196023, 0.22998862, 1.75081497])

In [8]:
randoms = np.random.uniform(0, 1, 4)
randoms

array([0.78011027, 0.75543462, 0.27066229, 0.82152855])

In [9]:
randoms  * [1, 2, 3, 4]

array([0.78011027, 1.51086924, 0.81198687, 3.28611419])

In [10]:
rs = np.random.RandomState(1)

In [11]:
rs.uniform(0, 1, 4)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [12]:
rs = np.random.RandomState(1)
rs.uniform(0, 1, 4)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [13]:
rs = np.random.RandomState(None)
rs.uniform(0, 1, 4)

array([0.48894612, 0.63144736, 0.65274225, 0.24631898])

In [14]:
rs = np.random.RandomState(None)
rs.uniform(0, 1, 4)

array([0.81507528, 0.88094374, 0.11763101, 0.94611482])

In [15]:
r1, r2 = rs.uniform(0, 1, 2)

In [16]:
r1, r2

(0.3892670128200675, 0.5463632856623215)

In [17]:
r1

0.3892670128200675

In [20]:
np.argmin([1, 2, 5, 0])

3